version: '3'

services:
  be:
    build:
      context: ./src/backend
      dockerfile: ../../docker/backend/Dockerfile
    container_name: mayan-b
    restart: unless-stopped
    ports:
      - "3000:3000"

  #=====================================================================#
  fe:
    build:
      context: ./src/frontend
      dockerfile: ../../docker/frontend/Dockerfile
    container_name: mayan-f
    restart: unless-stopped
    ports:
      - "3001:3001"